version: '3.9'
services:
  user-service:
    image: mysql:8.3.0
    container_name: mysql_user
    ports:
      - 3306:3306
    volumes:
      - ./database/user/mysql/data:/var/lib/mysql
      - ./database/user/mysql/config:/etc/mysql/conf.d
      - ./database/user/mysql/init:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_DATABASE: userservice
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    restart: always

  goods-service:
    image: mysql:8.3.0
    container_name: mysql_goods
    ports:
      - 3307:3306
    volumes:
      - ./database/goods/mysql/data:/var/lib/mysql
      - ./database/goods/mysql/config:/etc/mysql/conf.d
      - ./database/goods/mysql/init:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_DATABASE: goodsservice
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    restart: always

  order-service:
    image: mysql:8.3.0
    container_name: mysql-order
    ports:
      - 3308:3306
    volumes:
      - ./database/order/mysql/data:/var/lib/mysql
      - ./database/order/mysql/config:/etc/mysql/conf.d
      - ./database/order/mysql/init:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_DATABASE: orderservice
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    restart: always

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - 6379:6379
    volumes:
      - ./database/redis/data:/data
      - ./database/redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always